import ReactQueryProvider from '@/components/provider';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Expense Manager',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body suppressHydrationWarning={true} className={inter.className}>
        <ReactQueryProvider>
          <nav className='border-b p-2'>
            <ul className='flex gap-4'>
              <li>
                <Link href='/'>Accounts</Link>
              </li>
              <li>
                <Link href='/transactions'>Transactions</Link>
              </li>
              <li>
                <Link href='/budget'>Budget</Link>
              </li>
              <li>
                <Link href='/goal'>Goal</Link>
              </li>
              <li>
                <Link href='/investment'>Investment</Link>
              </li>
              <li>
                <Link href='/debts'>Debts</Link>
              </li>
            </ul>
          </nav>

          {children}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
