name: Check Budget Alerts

on:
  schedule:
    - cron: '0 9 * * *' # Daily at 09:00 AM UTC
  workflow_dispatch: # Optional: allows manual triggering

jobs:
  trigger-check-budget-alerts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Trigger Check Budget Alerts
        env:
          SCHEDULE_SERVICE_AUTH_TOKEN: ${{ secrets.SCHEDULE_SERVICE_AUTH_TOKEN }}
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
        run: |
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X GET \
            -H "X-Schedule-Auth: ${SCHEDULE_SERVICE_AUTH_TOKEN}" \
            "${BACKEND_URL}/schedule/check-budget-alerts")

          if [ "$RESPONSE" -ne 200 ]; then
            echo "::error ::Request failed with status $RESPONSE"
            exit 1
          fi
