name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        working-directory: [./backend, ./frontend]
    defaults:
      run:
        working-directory: ${{ matrix.working-directory }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build
        run: |
          if [ "${{ matrix.working-directory }}" = "./backend" ]; then
            bun run generate:build
          else
            bun run build
          fi