name: Generate Due Transactions

on:
  schedule:
    - cron: '0 * * * *' # Every hour UTC
  workflow_dispatch: # Manual trigger support

jobs:
  run-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        continue-on-error: true # Don't fail if checkout throws warnings

      - name: Trigger Generate Due Transactions
        env:
          SCHEDULE_SERVICE_AUTH_TOKEN: ${{ secrets.SCHEDULE_SERVICE_AUTH_TOKEN }}
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
        run: |
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X GET \
            -H "X-Schedule-Auth: ${SCHEDULE_SERVICE_AUTH_TOKEN}" \
            "${BACKEND_URL}/schedule/generate-due-transactions")

          if [ "$RESPONSE" -ne 200 ]; then
            echo "::error ::Request failed with status $RESPONSE"
            exit 1
          fi
